FROM ubuntu:22.04

# ARG DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        libatomic1 libquadmath0 \
        wget \
        sudo \
        python3 \
    ; \
    rm -rf /var/lib/apt/lists/*